using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using Assignment_Sa.Models;

namespace Assignment_Sa.Documents
{
    public class InvoiceDocument : IDocument
    {
        private readonly SaleMaster _sale;

        public InvoiceDocument(SaleMaster sale)
        {
            _sale = sale;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(30);

                // Header
                page.Header().Text("Invoice").FontSize(20).Bold().AlignCenter();

                // Content
                page.Content().Column(col =>
                {
                    // Customer Info
                    col.Item().Text($"Customer: {_sale.Customer?.Name}");
                    col.Item().Text($"Sale Date: {_sale.SaleDate:yyyy-MM-dd HH:mm}");

                    col.Item().PaddingVertical(10);

                    // Table
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.ConstantColumn(80);
                            columns.ConstantColumn(100);
                            columns.ConstantColumn(100);
                        });

                        // Table Header
                        table.Header(header =>
                        {
                            header.Cell().Text("Product").Bold();
                            header.Cell().Text("Quantity").Bold();
                            header.Cell().Text("Unit Price").Bold();
                            header.Cell().Text("Subtotal").Bold();
                        });

                        // Table Rows
                        foreach (var detail in _sale.SalesDetails)
                        {
                            table.Cell().Text(detail.Product?.Name ?? "N/A");
                            table.Cell().Text(detail.Quantity.ToString());
                            table.Cell().Text(detail.UnitPrice.ToString("C"));
                            table.Cell().Text(detail.SubTotal.ToString("C"));
                        }
                    });

                    // Add space before total
                    col.Item().PaddingVertical(10);

                    // Grand Total (bottom right)
                    col.Item().AlignRight().Text($"Grand Total: {_sale.TotalAmount:C}")
                        .FontSize(14).Bold();
                });

                // Footer
                page.Footer().AlignCenter().Text("Generated by Assignment_Sa").FontSize(10);
            });
        }
    }
}
